src/Entity/Membre.php
<?php

namespace App\Entity;

use App\Repository\MembreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass= MembreRepository::class)
 * @UniqueEntity(fields: ['email'], message: 'Un compte existe déjà avec cet email')
 */
// #[ORM\Entity(repositoryClass: MembreRepository::class)]
// #[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Membre implements UserInterface, PasswordAuthenticatedUserInterface
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    // #[ORM\Id]
    // #[ORM\GeneratedValue]
    // #[ORM\Column]
    private ?int $id = null;

    /**
     * @ORM\Column(type="string", length= 180, unique= true)
     */
    // #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    /**
     * @ORM\Column()
     */ //! Array ou quelque chose ?
    // #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    /**
     * @ORM\Column()
     */ //! Parenthèses ?
    // #[ORM\Column]
    private ?string $password = null;

    /**
     * @ORM\Column(type="string", length=255)
     */
    // #[ORM\Column(length: 255)]
    private ?string $nom = null;

    /**
     * @ORM\Column(type="string", length=255)
     */
    // #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    /**
     * @ORM\Column(type="string", length=255)
     */
    // #[ORM\Column(length: 255)]
    private ?string $civilite = null;

    /**
     * @ORM\Column(type="string", length=255)
     */
    // #[ORM\Column(length: 255)]
    private ?string $pseudo = null;

    /**
     * @ORM\Column(type= "datetime"))
     */
    // #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    /**
     * @ORM\Column(mappedBy= "membre", targetEntity= Commande::class, orphanRemoval= true)
     */
    // #[ORM\OneToMany(mappedBy: 'membre', targetEntity: Commande::class, orphanRemoval: true)]
    private Collection $commandes;


    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function setCivilite(string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setMembre($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getMembre() === $this) {
                $commande->setMembre(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getEmail() ;
    }

}

templates/app/commande.html.twig
{% extends "base.html.twig" %}

{% block body %}


{{ form_start(form, {
    attr: {
        novalidate: 'novalidate'
    }
}) }}

{# {{ form_row(form.membre) }} #}
{# {{ form_row(form.quantite) }}
{{ form_row(form.montant) }} #}
{# {{ form_row(form.produit) }} #}

<button type="submit" class="btn btn-warning">Enregistrer</button>

{{ form_end(form) }}


{% endblock %}

templates/app/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}MyShop{% endblock %}

{% block body %}

<h1 class="m-4">Bienvenue !</h1>
<h2>Dans ce site vous pourrez:</h2>
<ul>
    <li>Vous inscrire ou vous (dé)connecter</li>
    <li>Ajouter au panier des produits</li>
    <li>Accéder à l'administration si vous y êtes habilité</li>
    <li>Consulter votre page de profil</li>
    <li>Commander <strike>plusieurs produits (différents) en même temps</strike></li>
</ul>

<h2>Et ne pourrez pas:</h2>
<ul>
    <li>Fouiner dans le backoffice</li>
    <li>Modifier vos informations personnels</li>
</ul>

<small class="muted text-warning">Juste histoire de combler cette page</small>

{% endblock %}

templates/app/produits.html.twig
{% extends "base.html.twig" %}

{% block title %}Produits
{% endblock %}

{% block body %}

	<h1 class="text-center m-4">Nos produits</h1>


	<div class="row justify-content-around">
		{% for produit in produits %}
			<div class="card col-3 border-primary m-1" style="max-width: 20rem;">
				<div class="card-body">
					<h4 class="card-title text-center">{{ produit.titre }}</h4>
					<img src="{{ produit.photo }}" class="card-img">
					<ul class="list-group list-group-flush">
						<li class="list-group-item text-end">{{ produit.prix }}€</li>
						<li class="list-group-item">
						{% if produit.collection == 'h' %}
							Homme
						{% elseif produit.collection == 'f' %}
							Femme
						{% endif %} / 
						{{ produit.taille }}
						</li>
						<li class="list-group-item">{{ produit.description }}</li>
						<li class="list-group-item">En stock: {{ produit.stock }}</li>
					</ul>
			{% if produit.stock != 0 %}
				<a class="btn btn-primary" href="{{ path('cart_add', {id: produit.id}) }}">Ajouter au panier</a>
			{% else %}
				<div class="btn btn-secondary border disalbled">Stock vide</div>
			{% endif %}
				</div>
			</div>
		{% endfor %}
	</div>


{% endblock %}

templates/app/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %} Compte {% endblock %}

{% block body %}


<h1 class="text-center m-4">Mon profil</h1>

<div class="container-fluid">
<h2 class="col-12 text-center">
    {{ app.user.nom }}
    {{ app.user.prenom }}
    <small class="text-muted">@{{ app.user.pseudo }}</small>
</h2>

<div class="row my-4">
    <p class="col-4">
        {{ app.user.email }}<br>
        Statut: 
        {% if is_granted('ROLE_ADMIN') %}
            Administrateur
        {% endif %}
        <br>
        
        Inscrit depuis le: {{ app.user.dateEnregistrement|date('d/m/y') }}
    </p>
</div>

<h3 class="my-2">Commandes effectuées</h3>
<div class="list-group bg-light m-4">
    {% for commande in commandes %}
        {% if commande.membre.id == app.user.id %}
            <div class="list-group-item list-group-item-action list-group-item-light">
                <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ commande.id }}</h5>
                <small>{{ commande.dateEnregistrement|date('d/m/y') }}</small>
                </div>
                <p class="mb-1">{{ commande.produit.titre }}</p>
                <small>{{ commande.montant }}€</small>
            </div>
        {% endif %}
    {% endfor %}
  </div>

</div>



{% endblock %}